In [21]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

In [22]:
# File to load
nutrition_obesity = Path("../Resources/nutrition_physical_obesity_original.csv")

In [23]:
# Read file and store into Pandas DataFrames
nutrition_obesity_df = pd.read_csv(nutrition_obesity, encoding="ISO-8859-1")

In [24]:
# Show the first five rows.
nutrition_obesity_df.head()

,ï»¿YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2011,2011,AK,Alaska,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,2011.0,Value,...,"(64.845079957001, -147.722059036)",OWS,OWS1,Q036,VALUE,2,Race/Ethnicity,2 or more races,RACE,RACE2PLUS
1,2011,2011,AK,Alaska,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,2011.0,Value,...,"(64.845079957001, -147.722059036)",OWS,OWS1,Q036,VALUE,2,Race/Ethnicity,Other,RACE,RACEOTH
2,2011,2011,AK,Alaska,BRFSS,Physical Activity,Physical Activity - Behavior,Percent of adults who achieve at least 150 min...,2011.0,Value,...,"(64.845079957001, -147.722059036)",PA,PA1,Q044,VALUE,2,Gender,Female,GEN,FEMALE
3,2011,2011,AK,Alaska,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,2011.0,Value,...,"(64.845079957001, -147.722059036)",OWS,OWS1,Q036,VALUE,2,Age (years),35 - 44,AGEYR,AGEYR3544
4,2011,2011,AK,Alaska,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,2011.0,Value,...,"(64.845079957001, -147.722059036)",OWS,OWS1,Q037,VALUE,2,Income,"$15,000 - $24,999",INC,INC1525

## Data cleaning

In [25]:
# Show column names
nutrition_obesity_df.columns

Index(['ï»¿YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'Datasource',
       'Class', 'Topic', 'Question', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit ',
       'Sample_Size', 'Total', 'Age', 'Education', 'Gender', 'Income', 'Race',
       'GeoLocation', 'ClassID', 'TopicID', 'QuestionID', 'DataValueTypeID',
       'LocationID', 'StratificationCategory1', 'Stratification1',
       'StratificationCategoryId1', 'StratificationID1'],
      dtype='object')

In [44]:
# Remove specified columns from the DataFrame
columns_to_remove = [
    'ï»¿YearStart', 'LocationAbbr', 'Datasource', 'Class', 'Data_Value_Unit', 'Data_Value_Type', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
    'Data_Value_Footnote', 'Total', 'Age', 'Education', 'Gender', 'Income', 'Race', 'ClassID', 'TopicID', 'QuestionID', 'DataValueTypeID',
    'LocationID', 'StratificationCategory1', 'Stratification1', 'StratificationCategoryId1', 'StratificationID1', 'GeoLocation', 'Topic'
]

nutrition_obesity_rm_columns = nutrition_obesity_df.drop(columns=columns_to_remove)
nutrition_obesity_rm_columns.head()

,YearEnd,LocationDesc,Question,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size
0,2011,Alaska,Percent of adults aged 18 years and older who ...,23.3,16.1,32.4,128.0
1,2011,Alaska,Percent of adults aged 18 years and older who ...,35.5,22.7,50.9,63.0
2,2011,Alaska,Percent of adults who achieve at least 150 min...,21.7,19.1,24.6,1702.0
3,2011,Alaska,Percent of adults aged 18 years and older who ...,29.5,24.5,35.0,562.0
4,2011,Alaska,Percent of adults aged 18 years and older who ...,33.5,26.2,41.7,377.0

In [45]:
# Rename data columns
nutrition_obesity_renamed = nutrition_obesity_rm_columns.rename(columns={
    'YearEnd':'Year',
    'LocationDesc': 'State',
    'High_Confidence_Limit ': 'High_Confidence_Limit',
})

In [46]:
# Check info of the dataset
nutrition_obesity_renamed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104272 entries, 0 to 104271
Data columns (total 7 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Year                   104272 non-null  int64
 1   State                  104272 non-null  object
 2   Question               104272 non-null  object
 3   Data_Value             93505 non-null   float64
 4   Low_Confidence_Limit   93505 non-null   float64
 5   High_Confidence_Limit  93505 non-null   float64
 6   Sample_Size            93505 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 5.6+ MB

In [47]:
# Drop rows where any column has a null value
nutrition_obesity_renamed = nutrition_obesity_renamed.dropna()

In [48]:
# Check info of the dataset after cleaning
nutrition_obesity_renamed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93505 entries, 0 to 104271
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   93505 non-null  int64
 1   State                  93505 non-null  object
 2   Question               93505 non-null  object
 3   Data_Value             93505 non-null  float64
 4   Low_Confidence_Limit   93505 non-null  float64
 5   High_Confidence_Limit  93505 non-null  float64
 6   Sample_Size            93505 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 5.7+ MB

In [49]:
# Group by State, Question, Year then calculate the weighted average Data_Value for the filtered data
weighted_value_mean = nutrition_obesity_renamed.groupby(['State', 'Year', 'Question']).apply(
    lambda x: (x['Data_Value'] * x['Sample_Size']).sum() / x['Sample_Size'].sum()).reset_index(name='Weighted_Data_Value')

weighted_value_mean.head(20)

/var/folders/24/7rhj3_jn39lg7m0d74t2dp5w0000gn/T/ipykernel_88385/2587796038.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  weighted_value_mean = nutrition_obesity_renamed.groupby(['State', 'Year', 'Question']).apply(

,State,Year,Question,Weighted_Data_Value
0,Alabama,2011,Percent of adults aged 18 years and older who ...,34.795202
1,Alabama,2011,Percent of adults aged 18 years and older who ...,32.095245
2,Alabama,2011,Percent of adults who achieve at least 150 min...,42.237280
3,Alabama,2011,Percent of adults who achieve at least 150 min...,14.547775
4,Alabama,2011,Percent of adults who achieve at least 300 min...,24.008782
5,Alabama,2011,Percent of adults who engage in muscle-strengt...,23.933520
6,Alabama,2011,Percent of adults who engage in no leisure-tim...,33.082778
7,Alabama,2012,Percent of adults aged 18 years and older who ...,34.853446
8,Alabama,2012,Percent of adults aged 18 years and older who ...,33.074615
9,Alabama,2012,Percent of adults who engage in no leisure-tim...,27.716738
10,Alabama,2013,Percent of adults aged 18 years and older who ...,35.822401
11,Alabama,2013,Percent of adults aged 18 years and older who ...,32.590007
12,Alabama,2013,Percent of adults who achieve at least 150 min...,45.286950
13,Alabama,2013,Percent of adults who achieve at least 150 min...,15.475230
14,Alabama,2013,Percent of adults who achieve at least 300 min...,27.469468
15,Alabama,2013,Percent of adults who engage in muscle-strengt...,23.992560
16,Alabama,2013,Percent of adults who engage in no leisure-tim...,31.873032
17,Alabama,2014,Percent of adults aged 18 years and older who ...,33.611718
18,Alabama,2014,Percent of adults aged 18 years and older who ...,33.569185
19,Alabama,2014,Percent of adults who engage in no leisure-tim...,28.096160

In [50]:
# Check info of the average weighted_value
weighted_value_mean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3684 entries, 0 to 3683
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State                3684 non-null   object
 1   Year                 3684 non-null   int64
 2   Question             3684 non-null   object
 3   Weighted_Data_Value  3684 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 115.3+ KB

In [52]:
# Group by State, Question, Year then calculate the weighted average Low_Confidence_Limit for the filtered data
weighted_low_confidence_mean = nutrition_obesity_renamed.groupby(['State', 'Year', 'Question']).apply(
    lambda x: (x['Low_Confidence_Limit'] * x['Sample_Size']).sum() / x['Sample_Size'].sum()).reset_index(name='Weighted_Low_Confidence_Limit')

weighted_low_confidence_mean.head(20)

/var/folders/24/7rhj3_jn39lg7m0d74t2dp5w0000gn/T/ipykernel_88385/3169781522.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  weighted_low_confidence_mean = nutrition_obesity_renamed.groupby(['State', 'Year', 'Question']).apply(

,State,Year,Question,Weighted_Low_Confidence_Limit
0,Alabama,2011,Percent of adults aged 18 years and older who ...,32.045178
1,Alabama,2011,Percent of adults aged 18 years and older who ...,29.465123
2,Alabama,2011,Percent of adults who achieve at least 150 min...,39.336187
3,Alabama,2011,Percent of adults who achieve at least 150 min...,12.522509
4,Alabama,2011,Percent of adults who achieve at least 300 min...,21.581063
5,Alabama,2011,Percent of adults who engage in muscle-strengt...,21.472806
6,Alabama,2011,Percent of adults who engage in no leisure-tim...,30.440755
7,Alabama,2012,Percent of adults aged 18 years and older who ...,32.270524
8,Alabama,2012,Percent of adults aged 18 years and older who ...,30.544896
9,Alabama,2012,Percent of adults who engage in no leisure-tim...,25.417830
10,Alabama,2013,Percent of adults aged 18 years and older who ...,32.847816
11,Alabama,2013,Percent of adults aged 18 years and older who ...,29.769292
12,Alabama,2013,Percent of adults who achieve at least 150 min...,42.119681
13,Alabama,2013,Percent of adults who achieve at least 150 min...,13.262849
14,Alabama,2013,Percent of adults who achieve at least 300 min...,24.758984
15,Alabama,2013,Percent of adults who engage in muscle-strengt...,21.239802
16,Alabama,2013,Percent of adults who engage in no leisure-tim...,29.018875
17,Alabama,2014,Percent of adults aged 18 years and older who ...,31.071062
18,Alabama,2014,Percent of adults aged 18 years and older who ...,31.067635
19,Alabama,2014,Percent of adults who engage in no leisure-tim...,25.832105

In [53]:
# Check info of the average weighted_low_confidence_limit
weighted_low_confidence_mean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3684 entries, 0 to 3683
Data columns (total 4 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   State                          3684 non-null   object
 1   Year                           3684 non-null   int64
 2   Question                       3684 non-null   object
 3   Weighted_Low_Confidence_Limit  3684 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 115.3+ KB

In [54]:
# Group by State, Question, Year then calculate the weighted average High_Confidence_Limit for the filtered data
weighted_high_confidence_mean = nutrition_obesity_renamed.groupby(['State', 'Year', 'Question']).apply(
    lambda x: (x['High_Confidence_Limit'] * x['Sample_Size']).sum() / x['Sample_Size'].sum()).reset_index(name='Weighted_High_Confidence_Limit')

weighted_high_confidence_mean.head(20)

/var/folders/24/7rhj3_jn39lg7m0d74t2dp5w0000gn/T/ipykernel_88385/1175690015.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  weighted_high_confidence_mean = nutrition_obesity_renamed.groupby(['State', 'Year', 'Question']).apply(

,State,Year,Question,Weighted_High_Confidence_Limit
0,Alabama,2011,Percent of adults aged 18 years and older who ...,37.673758
1,Alabama,2011,Percent of adults aged 18 years and older who ...,34.848699
2,Alabama,2011,Percent of adults who achieve at least 150 min...,45.177558
3,Alabama,2011,Percent of adults who achieve at least 150 min...,16.922598
4,Alabama,2011,Percent of adults who achieve at least 300 min...,26.686562
5,Alabama,2011,Percent of adults who engage in muscle-strengt...,26.644358
6,Alabama,2011,Percent of adults who engage in no leisure-tim...,35.841304
7,Alabama,2012,Percent of adults aged 18 years and older who ...,37.542001
8,Alabama,2012,Percent of adults aged 18 years and older who ...,35.718472
9,Alabama,2012,Percent of adults who engage in no leisure-tim...,30.201307
10,Alabama,2013,Percent of adults aged 18 years and older who ...,38.926147
11,Alabama,2013,Percent of adults aged 18 years and older who ...,35.537520
12,Alabama,2013,Percent of adults who achieve at least 150 min...,48.496985
13,Alabama,2013,Percent of adults who achieve at least 150 min...,18.077163
14,Alabama,2013,Percent of adults who achieve at least 300 min...,30.387961
15,Alabama,2013,Percent of adults who engage in muscle-strengt...,27.004575
16,Alabama,2013,Percent of adults who engage in no leisure-tim...,34.903600
17,Alabama,2014,Percent of adults aged 18 years and older who ...,36.280383
18,Alabama,2014,Percent of adults aged 18 years and older who ...,36.217630
19,Alabama,2014,Percent of adults who engage in no leisure-tim...,30.527887

In [55]:
# Check info of the average weighted_high_confidence_limit
weighted_high_confidence_mean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3684 entries, 0 to 3683
Data columns (total 4 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   State                           3684 non-null   object
 1   Year                            3684 non-null   int64
 2   Question                        3684 non-null   object
 3   Weighted_High_Confidence_Limit  3684 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 115.3+ KB

In [56]:
# Group by State, Question, Year then calculate the total sample size for the filtered data
total_sample_size = nutrition_obesity_renamed.groupby(['State', 'Year', 'Question'])['Sample_Size'].sum().reset_index(name='Total_Sample_Size')

total_sample_size.head(20)

,State,Year,Question,Total_Sample_Size
0,Alabama,2011,Percent of adults aged 18 years and older who ...,43625.0
1,Alabama,2011,Percent of adults aged 18 years and older who ...,43662.0
2,Alabama,2011,Percent of adults who achieve at least 150 min...,42999.0
3,Alabama,2011,Percent of adults who achieve at least 150 min...,42725.0
4,Alabama,2011,Percent of adults who achieve at least 300 min...,42767.0
5,Alabama,2011,Percent of adults who engage in muscle-strengt...,44323.0
6,Alabama,2011,Percent of adults who engage in no leisure-tim...,44652.0
7,Alabama,2012,Percent of adults aged 18 years and older who ...,51744.0
8,Alabama,2012,Percent of adults aged 18 years and older who ...,51744.0
9,Alabama,2012,Percent of adults who engage in no leisure-tim...,53865.0
10,Alabama,2013,Percent of adults aged 18 years and older who ...,37297.0
11,Alabama,2013,Percent of adults aged 18 years and older who ...,37297.0
12,Alabama,2013,Percent of adults who achieve at least 150 min...,35287.0
13,Alabama,2013,Percent of adults who achieve at least 150 min...,34877.0
14,Alabama,2013,Percent of adults who achieve at least 300 min...,35062.0
15,Alabama,2013,Percent of adults who engage in muscle-strengt...,36330.0
16,Alabama,2013,Percent of adults who engage in no leisure-tim...,36859.0
17,Alabama,2014,Percent of adults aged 18 years and older who ...,48967.0
18,Alabama,2014,Percent of adults aged 18 years and older who ...,48967.0
19,Alabama,2014,Percent of adults who engage in no leisure-tim...,51615.0

In [57]:
total_sample_size.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3684 entries, 0 to 3683
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              3684 non-null   object
 1   Year               3684 non-null   int64
 2   Question           3684 non-null   object
 3   Total_Sample_Size  3684 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 115.3+ KB

In [58]:
# Merge all the results into one DataFrame
nutrition_obesity_final = weighted_value_mean.merge(weighted_low_confidence_mean, on=['State', 'Year', 'Question']) \
    .merge(weighted_high_confidence_mean, on=['State', 'Year', 'Question']) \
    .merge(total_sample_size, on=['State', 'Year', 'Question'])
nutrition_obesity_final.head()

,State,Year,Question,Weighted_Data_Value,Weighted_Low_Confidence_Limit,Weighted_High_Confidence_Limit,Total_Sample_Size
0,Alabama,2011,Percent of adults aged 18 years and older who ...,34.795202,32.045178,37.673758,43625.0
1,Alabama,2011,Percent of adults aged 18 years and older who ...,32.095245,29.465123,34.848699,43662.0
2,Alabama,2011,Percent of adults who achieve at least 150 min...,42.237280,39.336187,45.177558,42999.0
3,Alabama,2011,Percent of adults who achieve at least 150 min...,14.547775,12.522509,16.922598,42725.0
4,Alabama,2011,Percent of adults who achieve at least 300 min...,24.008782,21.581063,26.686562,42767.0

In [59]:
nutrition_obesity_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3684 entries, 0 to 3683
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   State                           3684 non-null   object
 1   Year                            3684 non-null   int64
 2   Question                        3684 non-null   object
 3   Weighted_Data_Value             3684 non-null   float64
 4   Weighted_Low_Confidence_Limit   3684 non-null   float64
 5   Weighted_High_Confidence_Limit  3684 non-null   float64
 6   Total_Sample_Size               3684 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 201.6+ KB

In [63]:
# Export DataFrame to a JSON file
nutrition_obesity_final.to_json('../Resources/nutrition_obesity_cleaned.json', orient='records')

In [61]:
# Export file as a CSV, without the Pandas index, but with the header
nutrition_obesity_final.to_csv("../Resources/nutrition_obesity_cleaned.csv", index=False, header=True)